pyodbc.cpython-311-x86_64-linux-gnu.so,sha256=9DKHRS_KkwEMZPADv7OGQsupu1XjguOp3476XlfL9cA,973136
pyodbc.pyi,sha256=JWNpdgmrxhNioTjW6OoAEcXELcGZobcMYzKtYlcJRuY,32320
pyodbc-4.0.38.dist-info/WHEEL,sha256=8KU227XctfdX2qUwyjQUO-ciQuZtmyPUCKmeGV6Byto,152
pyodbc-4.0.38.dist-info/LICENSE.txt,sha256=mFnIV3DJG3hmsPdpyTjjbWTQJgFBtSm5R7Tq2WiD6rQ,868
pyodbc-4.0.38.dist-info/RECORD,,
pyodbc-4.0.38.dist-info/METADATA,sha256=EjZZ8cmsdLrMbWGabwt6HcQGnUcZ89VyEbCiebo_njY,3160
pyodbc-4.0.38.dist-info/top_level.txt,sha256=Rb69vS-SNN_Bfh99vX7eCcvEAJoyzowG3u4R7W36Flw,8
