# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2023-03-17 14:57-0500\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: django/db/models/dated_model.py:20
msgid "Created at"
msgstr "Creado el"

#: django/db/models/dated_model.py:21
msgid "Modified at"
msgstr "Modificado el"

#: django/db/models/manager.py:42
#| msgid "Object does not exists."
msgid "OASIS Error. The object does not exists."
msgstr "El objeto no existe."

#: django/rest_framework/exceptions/api_exception.py:24
msgid "Object has not been created."
msgstr "El objeto no ha sido creado."

#: django/rest_framework/exceptions/api_exception.py:25
#: django/rest_framework/exceptions/api_exception.py:43
#: django/rest_framework/exceptions/api_exception.py:44
msgid "Generic error."
msgstr "Error genérico."

#: django/rest_framework/exceptions/api_exception.py:26
msgid "You are not authorized for this resource."
msgstr "No está autorizado para utilizar este recurso."

#: django/rest_framework/exceptions/api_exception.py:27
msgid "Object does not exists."
msgstr "El objeto no existe."

#: django/rest_framework/exceptions/api_exception.py:28
msgid "Data validation error."
msgstr "Error en validación de datos."

#: django/rest_framework/exceptions/api_exception.py:29
msgid "Data required not found."
msgstr "El dato requerido no existe."

#: django/rest_framework/exceptions/api_exception.py:30
msgid "Not controlled exception error."
msgstr "Error de excepción no controlada."

#: django/utils/code_generator.py:99
msgid "The generated values are invalid."
msgstr "El valor generado es inválido."

#: django/utils/error_messages.py:21
msgid "Error! The field is required."
msgstr "Error! El campo es requerido."

#: django/utils/error_messages.py:22
msgid "Error! Record has not been created."
msgstr "Error! El registro no ha sido creado."

#: django/utils/error_messages.py:23
msgid "Error! Record has not been updated."
msgstr "Error! El registro no ha sido actualizado."

#: django/utils/error_messages.py:24
msgid "Error! There is not record matching."
msgstr "Error! No existen registros que coincidan."

#: django/utils/error_messages.py:25
msgid "Error! Record can not be deleted."
msgstr "Error! El registro no ha sido eliminado."

#: django/utils/error_messages.py:26
msgid "Error! The data required not found."
msgstr "Error! Los datos requeridos no se encuentran."

#: django/utils/error_messages.py:27
msgid "Error at database."
msgstr "Error genérico en la base de datos."

#: django/utils/error_messages.py:28
msgid "Data required at request not found."
msgstr "El dato requerido no existe."

#: django/utils/error_messages.py:29
msgid "Error! Exception not controlled."
msgstr "Excepción no controlada"

#: django/utils/mail.py:73
msgid "Syntax error loading template '{}'"
msgstr "Error de sintaxis cargando la plantilla '{}'"

#: django/utils/mail.py:75
msgid "Template '{}' does not exist."
msgstr "La plantilla '{}' no existe."

#: django/utils/mail.py:100
msgid "Error sending email."
msgstr "Error enviando el correo."

#~ msgid "Data request not found."
#~ msgstr "El dato requerido no existe."
