CatchException/__init__.py,sha256=oD80YqvgwDRvz4p3pyD50L7vniKGqFTp32lbIQMgVuk,269
CatchException/__main__.py,sha256=exIbpImIFTzuCqHLVH5FpCcA2UaPb5_0wIWxoGG3zU0,1489
CatchException/mail_sender.py,sha256=CIPziLWE_YNPZxyifJPamDBGP00_UaAkLcN8-wFfY68,4350
catchexception-0.1.0.dist-info/LICENSE,sha256=qMxk-7EK-5Vzz1hbwJUFK9wUAumElP6HKmjKWkmDCjY,1104
catchexception-0.1.0.dist-info/METADATA,sha256=7VV2VXZU7PuTuUp7SIou9t6x8oVg8hLKLLyDLpdAIss,3419
catchexception-0.1.0.dist-info/WHEEL,sha256=pkctZYzUS4AYVn6dJ-7367OJZivF2e8RA9b_ZBjif18,92
catchexception-0.1.0.dist-info/entry_points.txt,sha256=XZc_EAfnUxFdXAq-TJWzKtr6JWJmelNvnn7Apu12gPM,59
catchexception-0.1.0.dist-info/top_level.txt,sha256=VmXK8LbKvaZ7rdymyf1DbaIa29aXo3yxbAW8RxDg2ac,15
catchexception-0.1.0.dist-info/RECORD,,
